<a href="https://colab.research.google.com/github/vladimyr02/cd-Vladimyr-Gonzalez-2023/blob/main/Taller7ClaseCD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Regresión logística**

Al igual que la regresión lineal múltiple, la regresión logística es una técnica para comprobar hipótesis y relaciones. Tiene la caracteristica adicional de permitir una variable de respuesta de tipo categórica.


![DiferenciaRegresionLineal](https://miro.medium.com/max/640/0*gKOV65tvGfY8SMem.png)

![image.png]()

##**Base de datos del titanic**

![image.png]()

In [ ]:
import pandas as pd
import statsmodels.api as sm

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/adiacla/bigdata/master/titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
#Verificar nulos
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df = df.drop('Cabin', axis = 1)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
df = df.dropna()
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

In [ ]:
df = df.drop('Name', axis = 1)
df = df.drop('Ticket', axis = 1)
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,male,22.0,1,0,7.2500,S
1,2,1,1,female,38.0,1,0,71.2833,C
2,3,1,3,female,26.0,0,0,7.9250,S
3,4,1,1,female,35.0,1,0,53.1000,S
4,5,0,3,male,35.0,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...
885,886,0,3,female,39.0,0,5,29.1250,Q
886,887,0,2,male,27.0,0,0,13.0000,S
887,888,1,1,female,19.0,0,0,30.0000,S
889,890,1,1,male,26.0,0,0,30.0000,C
890,891,0,3,male,32.0,0,0,7.7500,Q

In [ ]:
df["Sex2"] = 0
df.Sex2.loc[df.Sex=="female"] = 1
df.Sex2.loc[df.Sex=="male"] = 0
df

<ipython-input-8-8d0d7571fd9b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Sex2.loc[df.Sex=="female"] = 1
<ipython-input-8-8d0d7571fd9b>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Sex2.loc[df.Sex=="male"] = 0

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Sex2
0,1,0,3,male,22.0,1,0,7.2500,S,0
1,2,1,1,female,38.0,1,0,71.2833,C,1
2,3,1,3,female,26.0,0,0,7.9250,S,1
3,4,1,1,female,35.0,1,0,53.1000,S,1
4,5,0,3,male,35.0,0,0,8.0500,S,0
...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,female,39.0,0,5,29.1250,Q,1
886,887,0,2,male,27.0,0,0,13.0000,S,0
887,888,1,1,female,19.0,0,0,30.0000,S,1
889,890,1,1,male,26.0,0,0,30.0000,C,0
890,891,0,3,male,32.0,0,0,7.7500,Q,0

In [ ]:
df = df.drop('Sex', axis = 1)
df

     PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare Embarked  Sex2
0              1         0       3  22.0      1      0   7.2500        S     0
1              2         1       1  38.0      1      0  71.2833        C     1
2              3         1       3  26.0      0      0   7.9250        S     1
3              4         1       1  35.0      1      0  53.1000        S     1
4              5         0       3  35.0      0      0   8.0500        S     0
..           ...       ...     ...   ...    ...    ...      ...      ...   ...
885          886         0       3  39.0      0      5  29.1250        Q     1
886          887         0       2  27.0      0      0  13.0000        S     0
887          888         1       1  19.0      0      0  30.0000        S     1
889          890         1       1  26.0      0      0  30.0000        C     0
890          891         0       3  32.0      0      0   7.7500        Q     0

[712 rows x 9 columns]

In [ ]:
df["EmbarkedC"] = 0
df.EmbarkedC.loc[df.Embarked=="C"] = 1
df.EmbarkedC.loc[df.Embarked!="C"] = 0
df

<ipython-input-10-def598998efa>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.EmbarkedC.loc[df.Embarked=="C"] = 1
<ipython-input-10-def598998efa>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.EmbarkedC.loc[df.Embarked!="C"] = 0

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Embarked,Sex2,EmbarkedC
0,1,0,3,22.0,1,0,7.2500,S,0,0
1,2,1,1,38.0,1,0,71.2833,C,1,1
2,3,1,3,26.0,0,0,7.9250,S,1,0
3,4,1,1,35.0,1,0,53.1000,S,1,0
4,5,0,3,35.0,0,0,8.0500,S,0,0
...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,39.0,0,5,29.1250,Q,1,0
886,887,0,2,27.0,0,0,13.0000,S,0,0
887,888,1,1,19.0,0,0,30.0000,S,1,0
889,890,1,1,26.0,0,0,30.0000,C,0,1
890,891,0,3,32.0,0,0,7.7500,Q,0,0

In [ ]:
df["EmbarkedS"] = 0
df.EmbarkedS.loc[df.Embarked=="S"] = 1
df.EmbarkedS.loc[df.Embarked!="S"] = 0
df["EmbarkedQ"] = 0
df.EmbarkedQ.loc[df.Embarked=="Q"] = 1
df.EmbarkedQ.loc[df.Embarked!="Q"] = 0
df

<ipython-input-11-2fdab0c5144d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.EmbarkedS.loc[df.Embarked=="S"] = 1
<ipython-input-11-2fdab0c5144d>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.EmbarkedS.loc[df.Embarked!="S"] = 0
<ipython-input-11-2fdab0c5144d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.EmbarkedQ.loc[df.Embarked=="Q"] = 1
<ipython-input-11-2fdab0c5144d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.EmbarkedQ.loc[df.Embarked!="Q"] = 0

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Embarked,Sex2,EmbarkedC,EmbarkedS,EmbarkedQ
0,1,0,3,22.0,1,0,7.2500,S,0,0,1,0
1,2,1,1,38.0,1,0,71.2833,C,1,1,0,0
2,3,1,3,26.0,0,0,7.9250,S,1,0,1,0
3,4,1,1,35.0,1,0,53.1000,S,1,0,1,0
4,5,0,3,35.0,0,0,8.0500,S,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,39.0,0,5,29.1250,Q,1,0,0,1
886,887,0,2,27.0,0,0,13.0000,S,0,0,1,0
887,888,1,1,19.0,0,0,30.0000,S,1,0,1,0
889,890,1,1,26.0,0,0,30.0000,C,0,1,0,0
890,891,0,3,32.0,0,0,7.7500,Q,0,0,0,1

In [ ]:
df = df.drop('Embarked', axis = 1)
df

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Sex2,EmbarkedC,EmbarkedS,EmbarkedQ
0,1,0,3,22.0,1,0,7.2500,0,0,1,0
1,2,1,1,38.0,1,0,71.2833,1,1,0,0
2,3,1,3,26.0,0,0,7.9250,1,0,1,0
3,4,1,1,35.0,1,0,53.1000,1,0,1,0
4,5,0,3,35.0,0,0,8.0500,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,39.0,0,5,29.1250,1,0,0,1
886,887,0,2,27.0,0,0,13.0000,0,0,1,0
887,888,1,1,19.0,0,0,30.0000,1,0,1,0
889,890,1,1,26.0,0,0,30.0000,0,1,0,0
890,891,0,3,32.0,0,0,7.7500,0,0,0,1

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Sex2             int64
EmbarkedC        int64
EmbarkedS        int64
EmbarkedQ        int64
dtype: object

In [ ]:
x = df.iloc[:,[2,3,4,5,6,7,8,9,10]]
y = df.Survived
logit_model=sm.Logit(y,x)
result=logit_model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.444061
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:               Survived   No. Observations:                  712
Model:                          Logit   Df Residuals:                      703
Method:                           MLE   Df Model:                            8
Date:                Mon, 02 Oct 2023   Pseudo R-squ.:                  0.3419
Time:                        11:25:01   Log-Likelihood:                -316.17
converged:                       True   LL-Null:                       -480.45
Covariance Type:            nonrobust   LLR p-value:                 3.392e-66
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Pclass        -1.1993      0.165     -7.285      0.000      -1.522      -0.877
Age           -0.0433      0.008     -5.266      0.000      -0.059      -0.027
SibSp         -0.3632      0.129     -2.815      0.005      -0.616      -0.110
Parch         -0.0603      0.124     -0.486      0.627      -0.303       0.183
Fare           0.0014      0.003      0.566      0.572      -0.004       0.006
Sex2           2.6385      0.222     11.871      0.000       2.203       3.074
EmbarkedC      2.9989      0.582      5.157      0.000       1.859       4.139
EmbarkedS      2.5977      0.557      4.663      0.000       1.506       3.690
EmbarkedQ      2.1754      0.794      2.739      0.006       0.619       3.732
==============================================================================

In [ ]:
import statsmodels.api as sm
import itertools
import pandas as pd

# Definir las variables independientes
X_columns = [2, 3, 4, 5, 6, 7, 8, 9, 10]

# Crear una lista de diccionarios para registrar las combinaciones y sus métricas
results = []

# Iterar a través de todas las combinaciones posibles de variables independientes
for r in range(1, len(X_columns) + 1):
    combinations = itertools.combinations(X_columns, r)

    for combo in combinations:
        X_subset = df.iloc[:, list(combo)]
        logit_model = sm.Logit(y, X_subset)
        result = logit_model.fit()

        # Calcular el R-squared como métrica
        r_squared = 1.0 - result.llf / result.llnull

        # Registrar la combinación y su métrica en la lista
        results.append({'Combination': combo, 'R-squared': r_squared})

# Convertir la lista de resultados en un DataFrame
results_df = pd.DataFrame(results)

# Encontrar la mejor combinación basada en el R-squared
best_combination = results_df.loc[results_df['R-squared'].idxmax()]

# Mostrar la mejor combinación y su métrica
print("Mejor combinación de variables:", best_combination['Combination'])
print("Mejor R-squared:", best_combination['R-squared'])

Optimization terminated successfully.
         Current function value: 0.646769
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.671406
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.687447
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.693143
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.686284
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.644397
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.688879
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.663482
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.689416
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.645426
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.645782
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.636123
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.613061
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.477943
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.626534
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.646111
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.646617
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.670514
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.668862
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.627290
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.546480
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.652540
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.663108
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.670014
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.685564
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.671859
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.612464
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.681058
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.663481
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.684778
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.684601
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.630297
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.688670
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.657866
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.689408
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.644006
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.685365
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.631837
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.681886
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.644342
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.531615
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635128
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.659213
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.685148
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.659751
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.644205
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.634696
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.608852
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.477465
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.626534
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.645249
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.645292
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.636036
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.612533
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.476476
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.625738
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.645219
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.645598
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.610721
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.477764
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.617181
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635791
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.636019
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.473473
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.607211
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.612772
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.613006
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.470845
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.477932
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.477160
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.609544
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.626533
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.646104
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.665234
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.616566
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.530131
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.651207
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.663107
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.669314
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.626909
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.540568
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.650637
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.657398
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.667349
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.529969
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.621521
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.619997
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.626351
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.536565
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.521843
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.541563
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.652293
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.651796
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.659743
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.671793
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.610057
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.679849
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.656648
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.682806
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.611679
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.671057
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.628726
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.668998
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.612444
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.525231
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.604319
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.659032
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.678567
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.659663
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.630162
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.683715
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.631506
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.680489
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.630296
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.529692
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.621139
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.655239
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.685057
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.653218
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.644006
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.526719
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.634688
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.630789
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.681096
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.626024
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.528007
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.634969
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.515222
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.655482
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.634665
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.606775
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.475828
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.625733
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.644110
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.644041
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.607652
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.477273
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.617179
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.634672
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.634606
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.470082
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.602121
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.608849
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.608782
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.468829
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.477432
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.476634
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.593669
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.626533
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.645203
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.609125
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.476475
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.617091
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635691
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635942
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.470458
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.606964
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.612222
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.612493
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.469343
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.476476
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.475581
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.609341
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.625734
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.645197
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.472448
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.604242
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.610471
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.610673
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.470588
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.477757
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.476943
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.602962
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.617181
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635779
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.469402
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.473230
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.472841
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.603965
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.607208
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.612535
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.468159
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.470420
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.476924
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.604899
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.616032
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.529400
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.646514
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.656093
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.664105
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.502360
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.611567
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.613700
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.616234
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.519878
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.514369
         Iterations 6

In [ ]:
results_df

                      Combination  R-squared
0                            (2,)   0.041529
1                            (3,)   0.005018
2                            (4,)  -0.018754
3                            (5,)  -0.027195
4                            (6,)  -0.017031
..                            ...        ...
506     (2, 3, 4, 6, 7, 8, 9, 10)   0.341680
507     (2, 3, 5, 6, 7, 8, 9, 10)   0.333016
508     (2, 4, 5, 6, 7, 8, 9, 10)   0.310285
509     (3, 4, 5, 6, 7, 8, 9, 10)   0.285418
510  (2, 3, 4, 5, 6, 7, 8, 9, 10)   0.341929

[511 rows x 2 columns]

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Dividir el dataset en entrenamiento (80%) y prueba (20%)
train_df, test_df = train_test_split(df, test_size=0.2)

In [ ]:
train_df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Sex2             int64
EmbarkedC        int64
EmbarkedS        int64
EmbarkedQ        int64
dtype: object

In [ ]:
#Se definen las variables
x_train = train_df.iloc[:,[2,6,7]]
y_train = train_df.Survived
x_test = test_df.iloc[:,[2,6,7]]
y_test = test_df.Survived

In [ ]:
x_train = train_df.iloc[:,[2,3,4,5,6,7,8,9,10]]
y_train = train_df.Survived
logit_model=sm.Logit(y_train,x_train)
result=logit_model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.447882
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:               Survived   No. Observations:                  569
Model:                          Logit   Df Residuals:                      560
Method:                           MLE   Df Model:                            8
Date:                Mon, 02 Oct 2023   Pseudo R-squ.:                  0.3411
Time:                        12:18:10   Log-Likelihood:                -254.84
converged:                       True   LL-Null:                       -386.77
Covariance Type:            nonrobust   LLR p-value:                 1.995e-52
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Pclass        -1.1324      0.185     -6.114      0.000      -1.495      -0.769
Age           -0.0438      0.009     -4.806      0.000      -0.062      -0.026
SibSp         -0.3329      0.147     -2.267      0.023      -0.621      -0.045
Parch         -0.0760      0.159     -0.480      0.632      -0.387       0.235
Fare           0.0017      0.003      0.558      0.577      -0.004       0.008
Sex2           2.6293      0.244     10.756      0.000       2.150       3.108
EmbarkedC      2.8826      0.644      4.477      0.000       1.621       4.145
EmbarkedS      2.5075      0.628      3.991      0.000       1.276       3.739
EmbarkedQ      2.1729      0.870      2.497      0.013       0.468       3.878
==============================================================================

In [ ]:
import statsmodels.api as sm

# Selecciona las columnas de características en el conjunto de entrenamiento
x_train = train_df.iloc[:, [2, 3, 4, 5, 6, 7, 8, 9, 10]]

# El objetivo 'y_train' debe ser de train_df, no 'y'
y_train = train_df['Survived']

# Ajusta el modelo de regresión logística
logit_model = sm.Logit(y_train, sm.add_constant(x_train))  # Agrega una columna constante para el término constante
result = logit_model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.447882
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:               Survived   No. Observations:                  569
Model:                          Logit   Df Residuals:                      560
Method:                           MLE   Df Model:                            8
Date:                Mon, 02 Oct 2023   Pseudo R-squ.:                  0.3411
Time:                        12:18:12   Log-Likelihood:                -254.84
converged:                       True   LL-Null:                       -386.77
Covariance Type:            nonrobust   LLR p-value:                 1.995e-52
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.8907   7.61e+06   2.48e-07      1.000   -1.49e+07    1.49e+07
Pclass        -1.1324      0.185     -6.114      0.000      -1.495      -0.769
Age           -0.0438      0.009     -4.806      0.000      -0.062      -0.026
SibSp         -0.3329      0.147     -2.267      0.023      -0.621      -0.045
Parch         -0.0760      0.159     -0.480      0.632      -0.387       0.235
Fare           0.0017      0.003      0.558      0.577      -0.004       0.008
Sex2           2.6293      0.244     10.756      0.000       2.150       3.108
EmbarkedC      0.9919   7.61e+06    1.3e-07      1.000   -1.49e+07    1.49e+07
EmbarkedS      0.6167   7.61e+06   8.11e-08      1.000   -1.49e+07    1.49e+07
EmbarkedQ      0.2821   7.61e+06   3.71e-08      1.000   -1.49e+07    1.49e+07
==============================================================================

In [ ]:
# Realiza predicciones en el conjunto de prueba (o cualquier otro conjunto de datos)
x_train = train_df.iloc[:, [2, 3, 4, 5, 6, 7, 8, 9, 10]]
y_pred_prob = result.predict(sm.add_constant(x_train))

# Convierte las probabilidades en etiquetas binarias (0 o 1) usando un umbral
threshold = 0.5
y_pred_binary = (y_pred_prob > threshold).astype(int)

# Imprime las predicciones
print(y_pred_binary)

312    1
691    1
469    1
795    0
500    0
      ..
173    0
824    0
187    0
516    1
566    0
Length: 569, dtype: int64

In [ ]:
# Inicializa los contadores
TP_count = 0
FP_count = 0
FN_count = 0

# Define el umbral para convertir las probabilidades en etiquetas binarias
threshold = 0.5

# Itera a través de los valores reales y las predicciones
for y_real, y_prob in zip(y_train, y_pred_binary):
    # Convierte la probabilidad en etiqueta binaria
    y_pred_binary = 1 if y_prob > threshold else 0

    # Compara con el valor real y actualiza los contadores
    if y_real == 1 and y_pred_binary == 1:
        TP_count += 1
    elif y_real == 0 and y_pred_binary == 1:
        FP_count += 1
    elif y_real == 1 and y_pred_binary == 0:
        FN_count += 1

# Imprime los resultados
print(f'Verdaderos Positivos (TP): {TP_count}')
print(f'Falsos Positivos (FP): {FP_count}')
print(f'Falsos Negativos (FN): {FN_count}')

Verdaderos Positivos (TP): 172
Falsos Positivos (FP): 50
Falsos Negativos (FN): 66

In [ ]:
# Calcula la precisión y la exhaustividad
precision = TP_count / (TP_count + FP_count)
recall = TP_count / (TP_count + FN_count)

# Imprime los resultados
print(f'Precisión (Precision): {precision:.2f}')
print(f'Exhaustividad (Recall): {recall:.2f}')

Precisión (Precision): 0.77
Exhaustividad (Recall): 0.72